-- Vegetable Shop - MySQL 8.x database schema
-- Core tables: users, categories, products, carts, cart_items,
--              orders, order_details, reviews

CREATE DATABASE IF NOT EXISTS vegetable_shop
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE vegetable_shop;

-- =========================================================
-- 1. USERS
-- Passwords must contain BCrypt hashes generated by Spring Security.
-- Do not store plain-text passwords.
-- =========================================================
CREATE TABLE IF NOT EXISTS users (
    id BIGINT NOT NULL AUTO_INCREMENT,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NULL,
    address VARCHAR(255) NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    status BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT chk_users_role CHECK (role IN ('USER', 'ADMIN'))
) ENGINE = InnoDB;

-- =========================================================
-- 2. CATEGORIES
-- Categories should normally be disabled instead of hard-deleted.
-- =========================================================
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    description TEXT NULL,
    image VARCHAR(500) NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_categories_name UNIQUE (name)
) ENGINE = InnoDB;

-- =========================================================
-- 3. SUPPLIERS
-- Suppliers are disabled instead of deleted so historical Product data remains valid.
-- =========================================================
CREATE TABLE IF NOT EXISTS suppliers (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    phone VARCHAR(20) NULL,
    email VARCHAR(150) NULL,
    address VARCHAR(255) NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_suppliers_name UNIQUE (name)
) ENGINE = InnoDB;

-- =========================================================
-- 4. PRODUCTS
-- Each product belongs to exactly one category.
-- =========================================================
CREATE TABLE IF NOT EXISTS products (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    description TEXT NULL,
    price DECIMAL(15, 2) NOT NULL,
    quantity INT NOT NULL DEFAULT 0,
    image VARCHAR(500) NULL,
    category_id BIGINT NOT NULL,
    supplier_id BIGINT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT chk_products_price CHECK (price >= 0),
    CONSTRAINT chk_products_quantity CHECK (quantity >= 0),
    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id)
        REFERENCES categories (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_products_supplier
        FOREIGN KEY (supplier_id)
        REFERENCES suppliers (id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    INDEX idx_products_category_id (category_id),
    INDEX idx_products_supplier_id (supplier_id),
    INDEX idx_products_name (name),
    INDEX idx_products_status (status),
    INDEX idx_products_created_at (created_at)
) ENGINE = InnoDB;

-- =========================================================
-- 4. CARTS
-- Phase 6: one authenticated user has at most one cart.
-- =========================================================
CREATE TABLE IF NOT EXISTS carts (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_carts_user_id UNIQUE (user_id),
    CONSTRAINT fk_carts_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
) ENGINE = InnoDB;

-- =========================================================
-- 5. CART ITEMS
-- Phase 6: a product appears only once in a cart; quantity is updated in place.
-- =========================================================
CREATE TABLE IF NOT EXISTS cart_items (
    id BIGINT NOT NULL AUTO_INCREMENT,
    cart_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_cart_items_cart_product UNIQUE (cart_id, product_id),
    CONSTRAINT chk_cart_items_quantity CHECK (quantity > 0),
    CONSTRAINT fk_cart_items_cart
        FOREIGN KEY (cart_id)
        REFERENCES carts (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_cart_items_product
        FOREIGN KEY (product_id)
        REFERENCES products (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    INDEX idx_cart_items_product_id (product_id)
) ENGINE = InnoDB;

-- =========================================================
-- 6. ORDERS
-- total_amount is calculated again by the backend during checkout.
-- The initial payment method is COD.
-- =========================================================
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT NOT NULL AUTO_INCREMENT,
    order_code VARCHAR(30) NOT NULL,
    user_id BIGINT NOT NULL,
    receiver_name VARCHAR(100) NOT NULL,
    receiver_phone VARCHAR(20) NOT NULL,
    shipping_address VARCHAR(255) NOT NULL,
    note VARCHAR(500) NULL,
    total_amount DECIMAL(15, 2) NOT NULL,
    payment_method VARCHAR(30) NOT NULL DEFAULT 'COD',
    payment_status VARCHAR(20) NOT NULL DEFAULT 'UNPAID',
    payment_transaction_code VARCHAR(100) NULL,
    paid_at DATETIME NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_orders_order_code UNIQUE (order_code),
    CONSTRAINT chk_orders_total_amount CHECK (total_amount >= 0),
    CONSTRAINT uk_orders_payment_transaction_code
        UNIQUE (payment_transaction_code),
    CONSTRAINT chk_orders_payment_method
        CHECK (payment_method IN ('COD', 'VNPAY')),
    CONSTRAINT chk_orders_payment_status
        CHECK (payment_status IN ('UNPAID', 'PAID', 'FAILED', 'REFUNDED')),
    CONSTRAINT chk_orders_status
        CHECK (status IN (
            'PENDING', 'CONFIRMED', 'SHIPPING', 'COMPLETED', 'CANCELLED'
        )),
    CONSTRAINT fk_orders_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    INDEX idx_orders_user_id_created_at (user_id, created_at),
    INDEX idx_orders_status (status),
    INDEX idx_orders_created_at (created_at)
) ENGINE = InnoDB;

-- =========================================================
-- 7. ORDER DETAILS
-- product_name and price are snapshots at checkout time.
-- They must not be read from the current product price later.
-- =========================================================
CREATE TABLE IF NOT EXISTS order_details (
    id BIGINT NOT NULL AUTO_INCREMENT,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_name VARCHAR(150) NOT NULL,
    price DECIMAL(15, 2) NOT NULL,
    quantity INT NOT NULL,
    subtotal DECIMAL(15, 2) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_order_details_order_product UNIQUE (order_id, product_id),
    CONSTRAINT chk_order_details_price CHECK (price >= 0),
    CONSTRAINT chk_order_details_quantity CHECK (quantity > 0),
    CONSTRAINT chk_order_details_subtotal CHECK (subtotal >= 0),
    CONSTRAINT fk_order_details_order
        FOREIGN KEY (order_id)
        REFERENCES orders (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_order_details_product
        FOREIGN KEY (product_id)
        REFERENCES products (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    INDEX idx_order_details_product_id (product_id)
) ENGINE = InnoDB;

-- =========================================================
-- 8. REVIEWS
-- The Service layer must verify that the user bought the product in a
-- COMPLETED order before accepting a review.
-- =========================================================
CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    rating TINYINT NOT NULL,
    comment VARCHAR(1000) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_reviews_user_product UNIQUE (user_id, product_id),
    CONSTRAINT chk_reviews_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT fk_reviews_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_reviews_product
        FOREIGN KEY (product_id)
        REFERENCES products (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    INDEX idx_reviews_product_id_created_at (product_id, created_at)
) ENGINE = InnoDB;

-- =========================================================
-- SAMPLE DATA
-- No fixed user is inserted here because user passwords must be BCrypt hashes.
-- Phase 5 registers USER accounts through /register and can create an initial
-- ADMIN from APP_ADMIN_EMAIL / APP_ADMIN_PASSWORD environment variables.
-- =========================================================
INSERT IGNORE INTO categories
    (id, name, description, image, status)
VALUES
    (1, 'Rau củ', 'Các loại rau củ tươi sạch mỗi ngày', '/img/vegetable-item-1.jpg', TRUE),
    (2, 'Trái cây', 'Trái cây tươi trong nước và nhập khẩu', '/img/fruite-item-1.jpg', TRUE),
    (3, 'Thực phẩm sạch', 'Nhóm thực phẩm sạch được chọn lọc', '/img/best-product-1.jpg', TRUE);

INSERT IGNORE INTO suppliers
    (id, name, phone, email, address, status)
VALUES
    (1, 'Nông trại Xanh Việt', '0901000001', 'xanhviet@example.com', 'Đà Lạt, Lâm Đồng', TRUE),
    (2, 'Hợp tác xã Miền Tây', '0901000002', 'mientay@example.com', 'Cần Thơ', TRUE),
    (3, 'Fresh Food Việt Nam', '0901000003', 'freshfood@example.com', 'TP. Hồ Chí Minh', TRUE);

INSERT IGNORE INTO products
    (id, name, description, price, quantity, image, category_id, supplier_id, status)
VALUES
    (1, 'Bông cải xanh', 'Bông cải xanh tươi, phù hợp cho bữa ăn gia đình.', 35000.00, 50, '/img/vegetable-item-1.jpg', 1, 1, TRUE),
    (2, 'Ớt chuông', 'Ớt chuông giòn ngọt, giàu vitamin.', 45000.00, 40, '/img/vegetable-item-2.jpg', 1, 1, TRUE),
    (3, 'Chuối', 'Chuối chín tự nhiên, không sử dụng chất bảo quản.', 30000.00, 60, '/img/fruite-item-3.jpg', 2, 2, TRUE),
    (4, 'Cam', 'Cam tươi mọng nước, vị chua ngọt tự nhiên.', 55000.00, 45, '/img/fruite-item-4.jpg', 2, 2, TRUE),
    (5, 'Táo', 'Táo giòn, phù hợp dùng trực tiếp hoặc làm nước ép.', 75000.00, 35, '/img/fruite-item-6.jpg', 2, 3, TRUE);

-- Useful verification queries after importing this file:
-- SHOW TABLES;
-- SELECT * FROM categories;
-- SELECT * FROM products;
